# This is a standalone HTML builder - called from league_table_all.R
# Takes df, html_rows, n_pos, n_neg, med as inputs (they must exist in env)

build_html_page <- function(df, html_body, n_pos, n_neg, med) {

  lines <- c(
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<title>UK Universities: Real Income per Academic Staff 2015/16\u20132023/24</title>',
    '<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Source+Sans+3:wght@300;400;600&display=swap" rel="stylesheet">',
    '<style>',
    ':root{--bg:#FAFAF8;--surface:#FFFFFF;--border:#E8E4DC;--text:#1A1A1A;--muted:#6B6B60;--pos:#1A5276;--neg:#C0392B;--rg-accent:#7B241C;--rg-bg:#FDF6F5;}',
    '*{box-sizing:border-box;margin:0;padding:0;}',
    'body{font-family:"Source Sans 3",sans-serif;font-weight:300;background:var(--bg);color:var(--text);}',
    '.hero{background:#1A1A1A;color:#F5F3EE;padding:52px 48px 44px;}',
    '.hero h1{font-family:"Playfair Display",serif;font-size:clamp(1.5rem,3vw,2.4rem);line-height:1.2;margin-bottom:12px;max-width:780px;}',
    '.hero p{font-size:1rem;color:#B0ADA5;max-width:720px;line-height:1.6;margin-bottom:20px;}',
    '.hero .stats{display:flex;gap:32px;flex-wrap:wrap;margin-top:8px;}',
    '.stat-item{display:flex;flex-direction:column;}',
    '.stat-num{font-family:"Playfair Display",serif;font-size:1.8rem;color:#F5F3EE;}',
    '.stat-lbl{font-size:0.78rem;color:#888880;letter-spacing:0.05em;text-transform:uppercase;}',
    '.legend{display:flex;gap:24px;flex-wrap:wrap;padding:14px 48px;background:#242424;border-bottom:1px solid #333;font-size:0.8rem;color:#AAA;}',
    '.legend-item{display:flex;align-items:center;gap:7px;}',
    '.swatch{width:14px;height:14px;border-radius:2px;flex-shrink:0;}',
    '.container{max-width:1200px;margin:0 auto;padding:32px 24px 64px;}',
    '.table-wrap{overflow-x:auto;border-radius:6px;box-shadow:0 2px 12px rgba(0,0,0,0.06);}',
    'table{width:100%;border-collapse:collapse;background:var(--surface);font-size:0.875rem;}',
    'thead th{background:#1A1A1A;color:#E0DDD8;padding:11px 14px;text-align:left;font-weight:600;font-size:0.75rem;letter-spacing:0.04em;text-transform:uppercase;white-space:nowrap;position:sticky;top:0;z-index:2;}',
    'thead th.num,thead th.bar-cell{text-align:right;}',
    'tr{border-bottom:1px solid var(--border);transition:background 0.15s;}',
    'tr:last-child{border-bottom:none;}',
    'tr:hover{background:#F4F2EE;}',
    'tr.rg-row{background:var(--rg-bg);}',
    'tr.rg-row:hover{background:#FAE8E6;}',
    'td{padding:9px 14px;vertical-align:middle;}',
    'td.rank{color:var(--muted);font-size:0.78rem;width:36px;font-weight:600;}',
    'td.uni-name{font-weight:400;min-width:220px;}',
    'td.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap;color:#333;}',
    '.rg-badge{display:inline-block;background:var(--rg-accent);color:white;font-size:0.62rem;font-weight:600;padding:1px 5px;border-radius:3px;letter-spacing:0.04em;vertical-align:middle;margin-left:5px;}',
    'td.bar-cell{width:220px;padding-right:10px;}',
    '.bar-wrap{display:flex;align-items:center;gap:7px;}',
    '.bar{height:13px;border-radius:2px;min-width:2px;flex-shrink:0;}',
    '.bar-label{font-size:0.8rem;font-variant-numeric:tabular-nums;white-space:nowrap;font-weight:600;}',
    '.bar-label.pos{color:var(--pos);}',
    '.bar-label.neg{color:var(--neg);}',
    '.toolbar{display:flex;align-items:center;gap:16px;flex-wrap:wrap;margin-bottom:16px;}',
    '.search-bar{display:flex;align-items:center;gap:12px;}',
    '.search-bar input{padding:9px 14px;border:1px solid var(--border);border-radius:4px;font-family:inherit;font-size:0.9rem;width:280px;outline:none;background:white;color:var(--text);}',
    '.search-bar input:focus{border-color:#888;}',
    '.search-bar label{font-size:0.85rem;color:var(--muted);}',
    '.filter-btns{display:flex;gap:8px;flex-wrap:wrap;}',
    '.filter-btn{padding:6px 14px;border:1px solid var(--border);border-radius:20px;background:white;font-family:inherit;font-size:0.8rem;cursor:pointer;color:var(--muted);transition:all 0.15s;}',
    '.filter-btn.active,.filter-btn:hover{background:#1A1A1A;color:white;border-color:#1A1A1A;}',
    '.count-label{font-size:0.82rem;color:var(--muted);margin-left:auto;}',
    'footer{text-align:center;padding:28px;font-size:0.78rem;color:var(--muted);border-top:1px solid var(--border);line-height:1.7;}',
    '@media (max-width:640px){.hero{padding:32px 20px 28px;}.legend{padding:12px 20px;}.container{padding:20px 12px 48px;}td.bar-cell{display:none;}}',
    '</style>',
    '</head>',
    '<body>',
    '<div class="hero">',
    '  <h1>Real income per academic staff,<br>2015/16 to 2023/24</h1>',
    '  <p>How UK universities changed in financial productivity per academic, adjusted to 2026 prices. Most institutions lost ground in real terms as staff growth outpaced income growth.</p>',
    '  <div class="stats">',
    paste0('    <div class="stat-item"><span class="stat-num">', nrow(df), '</span><span class="stat-lbl">Universities</span></div>'),
    paste0('    <div class="stat-item"><span class="stat-num">', n_pos, '</span><span class="stat-lbl">Gained in real terms</span></div>'),
    paste0('    <div class="stat-item"><span class="stat-num">', n_neg, '</span><span class="stat-lbl">Lost in real terms</span></div>'),
    paste0('    <div class="stat-item"><span class="stat-num">', sprintf("%+.0f%%", med), '</span><span class="stat-lbl">Median change</span></div>'),
    '  </div>',
    '</div>',
    '<div class="legend">',
    '  <div class="legend-item"><div class="swatch" style="background:#1A5276"></div> Other HEI &mdash; gained</div>',
    '  <div class="legend-item"><div class="swatch" style="background:#A9CCE3"></div> Other HEI &mdash; lost</div>',
    '  <div class="legend-item"><div class="swatch" style="background:#C0392B"></div> Russell Group &mdash; gained</div>',
    '  <div class="legend-item"><div class="swatch" style="background:#E8A09A"></div> Russell Group &mdash; lost</div>',
    '</div>',
    '<div class="container">',
    '  <div class="toolbar">',
    '    <div class="search-bar">',
    '      <label for="search">Search:</label>',
    '      <input type="text" id="search" placeholder="University name&#8230;" oninput="filterTable()">',
    '    </div>',
    '    <div class="filter-btns">',
    '      <button class="filter-btn active" onclick="setFilter(this,\'all\')">All</button>',
    '      <button class="filter-btn" onclick="setFilter(this,\'rg\')">Russell Group only</button>',
    '      <button class="filter-btn" onclick="setFilter(this,\'pos\')">Gained</button>',
    '      <button class="filter-btn" onclick="setFilter(this,\'neg\')">Lost</button>',
    '    </div>',
    '    <span class="count-label" id="count-label"></span>',
    '  </div>',
    '  <div class="table-wrap">',
    '    <table id="league-table">',
    '      <thead><tr>',
    '        <th>Rank</th><th>University</th>',
    '        <th class="num">Acad staff<br>2015/16</th>',
    '        <th class="num">Acad staff<br>2023/24</th>',
    '        <th class="num">IPS 2015/16</th>',
    '        <th class="num">IPS 2023/24</th>',
    '        <th class="bar-cell" style="text-align:left">Real change (2026 prices)</th>',
    '      </tr></thead>',
    '      <tbody id="table-body">',
    html_body,
    '      </tbody>',
    '    </table>',
    '  </div>',
    '</div>',
    '<footer>',
    '  Income per academic staff (IPS) = total consolidated income (HESA DT031) &divide; total academic staff headcount (HESA DT025), &pound;000s.<br>',
    '  Deflated to 2026 prices using ONS CPI D7BT (2015=100): 2015/16 avg&nbsp;=&nbsp;100.3, 2023/24 avg&nbsp;=&nbsp;132.4, 2026 est&nbsp;=&nbsp;144.0.<br>',
    '  Source: HESA open data. Analysis: original research.',
    '</footer>',
    '<script>',
    '  let activeFilter = "all";',
    '  function updateCount() {',
    '    const rows = document.querySelectorAll("#table-body tr");',
    '    let v = 0;',
    '    rows.forEach(r => { if (r.style.display !== "none") v++; });',
    '    document.getElementById("count-label").textContent = v + " of " + rows.length + " universities shown";',
    '  }',
    '  function filterTable() {',
    '    const q = document.getElementById("search").value.toLowerCase();',
    '    const rows = document.querySelectorAll("#table-body tr");',
    '    rows.forEach(row => {',
    '      const name = row.querySelector(".uni-name").textContent.toLowerCase();',
    '      const isRG  = row.classList.contains("rg-row");',
    '      const isPos = row.querySelector(".bar-label.pos") !== null;',
    '      const ok = name.includes(q) && (',
    '        activeFilter === "all" ? true :',
    '        activeFilter === "rg"  ? isRG :',
    '        activeFilter === "pos" ? isPos :',
    '        activeFilter === "neg" ? !isPos : true);',
    '      row.style.display = ok ? "" : "none";',
    '    });',
    '    updateCount();',
    '  }',
    '  function setFilter(btn, f) {',
    '    activeFilter = f;',
    '    document.querySelectorAll(".filter-btn").forEach(b => b.classList.remove("active"));',
    '    btn.classList.add("active");',
    '    filterTable();',
    '  }',
    '  updateCount();',
    '</script>',
    '</body>',
    '</html>'
  )

  paste(lines, collapse = "\n")
}
